FIX: type-hinted declaration only
PositiveTechnologies/PT.PM pull request #224
Opened 2019-04-27 10:53 UTC by inkoit

In case we have annassign with no assignment.
Also, test case using test from my grammar fix

2019-05-07 14:07 UTC, codeFather2 requested changes

2019-05-07 14:07 UTC, codeFather2 commented on Sources/PT.PM.PythonParseTreeUst.Tests/PythonConverterTests.cs
> +        public void Convert_PythonFiles_WithoutErrors(string langFolder, string examplesFolder)
I think it would be great to rename the folder to `examples`, for consistency with all other antlr-languages

2019-05-07 14:07 UTC, codeFather2 commented on Sources/PT.PM.PythonParseTreeUst/PythonAntlrConverter.cs
> +            // In case we have an asterisk instead of argument
Isn't the asterisk a token? Ignoring it is not a good idea, as in the future it may affect the matching. I think it's good to handle it as `IdToken('*')`

2019-05-07 14:07 UTC, codeFather2 commented on Sources/PT.PM.PythonParseTreeUst/PythonAntlrConverter.cs
> +                : ProcessAssign(context, assign_part);
👍

2019-05-07 14:07 UTC, codeFather2 commented on Sources/PT.PM.PythonParseTreeUst/PythonAntlrConverter.cs
> +        public Ust VisitFinally_clause([NotNull] PythonParser.Finally_clauseContext context)
👍

2019-05-13 08:11 UTC, inkoit commented on Sources/PT.PM.PythonParseTreeUst.Tests/PythonConverterTests.cs
> +        public void Convert_PythonFiles_WithoutErrors(string langFolder, string examplesFolder)
Done

2019-05-13 08:15 UTC, inkoit commented on Sources/PT.PM.PythonParseTreeUst/PythonAntlrConverter.cs
> +            // In case we have an asterisk instead of argument
I don't really understand PT.PM internals still. Does the last commit implements this behaviour?

2019-10-18 10:19 UTC, KvanTTT commented
I'm closing because it is already fixed by other changes.

2019-10-18 10:19 UTC, closed without merging